### ISSUE TITLE
Error state

### ISSUE THREAD

**Issue by parse-code** [tonylukasavage/pathmenu.js#13]
When I click the plus button quickly, I will get a error state. http://cl.ly/Dygk

**Comment by tonylukasavage** [comment]
I am unable to recreate this issue. Can you give a more detailed account of how you are generating that error state?

**Comment by parse-code** [comment]
Check this screencast:http://cl.ly/Dy04/pathmenu.mov

**Comment by tonylukasavage** [comment]
Do you have the latest code? I remember having a similar issue in the past, but I thought I resolved it with better checking of the `open` and `close` states if the menu.

**Comment by parse-code** [comment]
I just download and run the code today.

**Comment by tonylukasavage** [comment]
I'll beat on it a little more and see if I can recreate it on my end. Just to help me out a bit, what version of the Titanium SDK are you using, and what version of the iOS simulator are testing with?

**Comment by parse-code** [comment]
Titanium SDK: 1.8.1
iOS simulator: 5.0

**Comment by tonylukasavage** [comment]
I was able to recreate it. I noticed that opening or closing the menu again "resets" the issue, so it's not stuck in  that error state. Have you found that to be the case as well? It's a bug for sure, just trying to determine how bad.

**Comment by parse-code** [comment]
Yes, the issue will be 'reset' by click plus button again.
