### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by iantearle** [tonylukasavage/pathmenu.js#16]
This might be due to Titanium SDK, I'm testing 1.8.2, but I get hundreds of debug messages as follows when click on the plus button?

[DEBUG] ignoring new layout while animating in layout Child..

Any ideas how to suppress this?

**Comment by tonylukasavage** [comment]
That is in fact an underlying Titanium message that has to do with the way layouts are rendered during animations. It can be safely ignored.

**Comment by iantearle** [comment]
Lovely. Thanks for clarification. And speed. I have completely changed the menu, I just want the animation effects so I can make something like this: http://dribbble.com/shots/360236-Hello-tool-wheel

**Comment by tonylukasavage** [comment]
How does the interaction work on that hello tool wheel? That looks similar to something I was thinking of based on the pathmenu.js code as well.

**Comment by iantearle** [comment]
Hello is a very long way off for me at the moment, It was supposed to be see who's around me social network, integrated into any app interface - (Titanium built of course), a module that could be installed inside an app to give it instant local social networking capability. 

I wanted something new and different, keeping the UI clean for the next release of Heritage, http://hrt.gs/ its accessible from longclick, here is a video preview...

http://cl.ly/FcZc
