### ISSUE TITLE
Underlying Events Blocked

### ISSUE THREAD

**Issue by stevenscg** [tonylukasavage/pathmenu.js#17]
It appears that if the menu is used on top of a tableview or other element, the tableview click handler events are being blocked.  Simply removing the menu and rebuilding shows that the click handlers are working.

This was found by creating a new project using the "Master/Detail" template from Studio and applying the menu to the master view or window (it didn't seem to matter).

Platform: IOS, Ti Studio 2, SDK 2.x

**Comment by tonylukasavage** [comment]
I put a quick fix in place. Ideally, though, this would work best by all components of the menu being added directly to the containing parent, so events are never stolen, even when the menu is open.

**Comment by stevenscg** [comment]
Thanks!  I'll check it out.
